### ISSUE TITLE
Badges should have names other than the package name

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/cloud-opensource-python#162]
How about:

"Self Compatibility" => "internal compatibility"
"Google Compatibility" => "cross compatibility"
"Dependency Version Status" => "up-to-date dependencies"

**Comment by liyanhui1228** [comment]
The `compatibility_lib` on the badge is actually the package name being checked (our package name is compatibility_lib). But changing the package name displayed on badge to the check type sounds good!
